services:
  db:
    image: mysql:8.0.45-bookworm
    container_name: mediqdb
    restart: always
    env_file:
      - ../.env.dev
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"] # bratletata da sprat da go karat na hardcoded values?
      start_period: 15s
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - mediqdb_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - mediq_be

  app:
    build: ../src/bins/MediqAppoint
    container_name: mediqapp
    depends_on:
      db:
        condition: service_healthy
        required: true
    env_file:
      - ../.env.dev
    ports:
      - 8080:8080
    networks:
      - mediq_be

  frontend:
    build: ../src/bins/frontend
    container_name: frontend
    depends_on:
      - app
    ports:
      - 3000:3000
    networks:
      - mediq_be

volumes:
  mediqdb_data:

networks:
  mediq_be:
